[2021-08-13T11:35:08.040-0400 DEBUG yapapi] Yapapi version: 0.6.3, script: blender.py, working directory: /home/sensorweb/MS/decentralized-computing/golem/yapapi/examples/blender
[2021-08-13T11:35:08.041-0400 INFO yapapi] Using log file `blender-yapapi-2021-08-13_11.35.08.log`; in case of errors look for additional information there
[2021-08-13T11:35:08.254-0400 DEBUG ya_payment.rest] request: {'method': 'GET', 'url': 'http://127.0.0.1:7465/payment-api/v1/requestorAccounts', 'timeout': 300, 'headers': {'Accept': 'application/json', 'authorization': 'Bearer insert-your-32-char-app-key-here', 'User-Agent': 'OpenAPI-Generator//python', 'Content-Type': 'application/json'}}
[2021-08-13T11:35:08.256-0400 DEBUG ya_payment.rest] response body: b'Invalid application key'
[2021-08-13T11:35:08.257-0400 DEBUG yapapi.events] ShutdownFinished(exc_info=(<class 'ya_payment.exceptions.ApiException'>, ApiException(), <traceback object at 0x7f75fefff4c0>))
Traceback (most recent call last):
  File "/home/sensorweb/.envs/yagna-python-tutorial/lib/python3.8/site-packages/yapapi/engine.py", line 245, in __aenter__
    self.payment_decorator = _Engine.PaymentDecorator(await self._create_allocations())
  File "/home/sensorweb/.envs/yagna-python-tutorial/lib/python3.8/site-packages/yapapi/engine.py", line 322, in _create_allocations
    async for account in self._payment_api.accounts():
  File "/home/sensorweb/.envs/yagna-python-tutorial/lib/python3.8/site-packages/yapapi/rest/payment.py", line 193, in accounts
    for account_obj in cast(Iterable[Account], await self._api.get_requestor_accounts()):
  File "/home/sensorweb/.envs/yagna-python-tutorial/lib/python3.8/site-packages/ya_payment/api_client.py", line 206, in __call_api
    raise e
  File "/home/sensorweb/.envs/yagna-python-tutorial/lib/python3.8/site-packages/ya_payment/api_client.py", line 194, in __call_api
    response_data = await self.request(
  File "/home/sensorweb/.envs/yagna-python-tutorial/lib/python3.8/site-packages/ya_payment/rest.py", line 192, in GET
    return await self.request(
  File "/home/sensorweb/.envs/yagna-python-tutorial/lib/python3.8/site-packages/ya_payment/rest.py", line 180, in request
    raise ApiException(http_resp=r)
ya_payment.exceptions.ApiException: (401)
Reason: Unauthorized
HTTP response headers: <CIMultiDictProxy('Content-Length': '23', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Aug 2021 15:35:08 GMT')>
HTTP response body: Invalid application key

[2021-08-13T11:35:08.258-0400 INFO yapapi.summary] Total cost: 0
[2021-08-13T11:35:08.258-0400 ERROR yapapi.summary] Error when shutting down Executor: (401)
Reason: Unauthorized
HTTP response headers: <CIMultiDictProxy('Content-Length': '23', 'Content-Type': 'text/plain; charset=utf-8', 'Date': 'Fri, 13 Aug 2021 15:35:08 GMT')>
HTTP response body: Invalid application key

[2021-08-13T11:35:08.259-0400 DEBUG yapapi.utils] AsyncWrapper's worker task cancelled
